name: "Tests"

on: [push]

jobs:
  tests:
    name: Tests with Ruby v${{ matrix.ruby }}
    runs-on: "ubuntu-latest"

    env:
      RAILS_ENV: test

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Running tests
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: 5c1f1e8b5833596f0e9fb4a56d61a186d0a4cd2289f2224effdba5a3a8d22015
        with:
          debug: true
          coverageCommand: bin/test
