name: "Tests"

on: [push]

jobs:
  tests:
    name: Tests with Ruby v${{ matrix.ruby }}
    runs-on: "ubuntu-latest"

    env:
      RAILS_ENV: test

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0.4"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Running tests
        env:
          CC_TEST_REPORTER_ID: 747d63fc771e9c7bade64cce52fce297415adad9904a7523691ed934201723aa
        run: ./bin/test
